// Diccionarios de idioma (ES/EN) y traducción pura (sin DOM). Testeable con `node --test`.
export const I18N={
es:{
 'welcome.eyebrow':'Belleza profesional · Experiencia virtual','welcome.h1':'Tu belleza.<br>A tu manera.','welcome.p':'Descubre cómo podrían quedarte nuestros productos.','welcome.start':'Comenzar','welcome.small':'Una experiencia de belleza · Sin compromiso',
 'consent.eyebrow':'Tu privacidad es lo primero','consent.h2':'Utilizaremos tu cámara para crear esta experiencia de prueba virtual.','consent.p':'El vídeo se procesa en este dispositivo; no se envía ni se guarda. Solo se guarda una imagen si la descargas. Si calibras el color, la calibración queda guardada en este navegador. La cámara se apaga al salir.','consent.accept':'Aceptar y continuar','consent.no':'Ahora no',
 'scan.eyebrow':'Prueba virtual','scan.cancel':'Cancelar','scan.retry':'Reintentar cámara','scan.c0':'Rostro detectado','scan.c1':'Iluminación adecuada','scan.c2':'Posición correcta',
 'mirror.back':'← Atrás','mirror.backAria':'Volver','mirror.look':'Mi look','mirror.compare':'Comparar','mirror.save':'Guardar','mirror.calibrate':'Calibrar','mirror.tag':'Elige un producto para empezar.','mirror.before':'Antes','mirror.after':'Después','mirror.subtle':'Sutil','mirror.intense':'Intensa','mirror.intensity':'Intensidad','mirror.catalog':'Catálogo de demostración · Productos, precios y ubicación ficticios',
 'store.title':'Ubicación de ejemplo','store.close':'Cerrar','store.aisle':'Pasillo de ejemplo','store.section':'Sección','store.demo':'El catálogo y la ubicación son datos ficticios de demostración; no representan existencias reales.',
 'save.eyebrow':'Tu selección','save.h2':'Tu look, listo para guardar','save.placeholder':'La vista previa de tu look aparecerá aquí.','save.download':'Descargar imagen','save.finish':'Terminar','save.keep':'Seguir probando','save.previewAlt':'Vista previa del look creado','save.needProduct':'Prueba al menos un producto antes de guardar tu look.','save.align':'Alinea tu rostro con la cámara antes de guardar.','save.preparing':'Preparando la imagen…','save.ready':'Imagen creada en este dispositivo. Descárgala para guardarla; no se ha subido a ningún servidor.','save.error':'No se pudo preparar la imagen. Vuelve al espejo e inténtalo de nuevo.','save.errorShort':'No se pudo preparar la imagen.',
 'cam.prep':'Preparando la cámara','cam.permission':'Acepta el permiso del navegador para continuar.','cam.face':'Coloca tu rostro aquí','cam.looking':'Mirando a la cámara','cam.loadingFace':'Cargando detección facial…','cam.lost':'Se ha perdido la cámara','cam.lostMsg':'La cámara se ha desconectado. Comprueba el dispositivo y vuelve a intentarlo.','cam.resume':'No se pudo reanudar la cámara. Vuelve al inicio para intentarlo de nuevo.','cam.failTitle':'No se pudo iniciar la prueba','cam.unsupported':'Este navegador no ofrece acceso a la cámara. Prueba con Chrome o Edge.','cam.denied':'No se concedió permiso para la cámara. Actívalo en el navegador y vuelve a intentarlo.','cam.notfound':'No se encontró ninguna cámara conectada.','cam.busy':'La cámara está ocupada por otra aplicación. Ciérrala y vuelve a intentarlo.','cam.security':'Abre la aplicación desde localhost o una conexión HTTPS para usar la cámara.','cam.generic':'No se pudo cargar la cámara o la detección facial. Comprueba tu conexión y vuelve a intentarlo.',
 'scan.perfect':'Perfecto.','scan.preparing':'Estamos preparando tu experiencia.',
 'hint.noFace':'No vemos tu rostro. Mira a la cámara.','hint.dark':'Poca luz: acércate a una zona más iluminada.','hint.yaw':'Mira a la cámara para ver el resultado completo.','hint.detectFail':'La detección facial se ha interrumpido. Vuelve a iniciar la prueba.','hint.cpu':'Modo de compatibilidad activado: la calidad se ajusta automáticamente.',
 'quality.auto':'Automática','quality.high':'Alta','quality.fluid':'Fluida','quality.btn':l=>`Calidad: ${l}`,
 'cat.base':'Base','cat.blush':'Colorete','cat.lips':'Labios','cat.eyes':'Ojos','cat.glow':'Iluminador','cat.contour':'Contorno','cat.liner':'Delineador','cat.lash':'Pestañas','cat.brow':'Cejas',
 'fin.Mate':'Mate','fin.Luminoso':'Luminoso','fin.Satinado':'Satinado','fin.Brillo':'Brillo','fin.Glitter':'Glitter','fin.Suave':'Suave','fin.Definido':'Definido','fin.Definida':'Definida','fin.Fino':'Fino','fin.Clásico':'Clásico','fin.Alado':'Alado','fin.Natural':'Natural','fin.Volumen':'Volumen',
 'prod.try':'Probar','shade.selected':'Tu selección','look.empty':'Aún no has probado nada.','look.ideas':'Ideas de combinación del catálogo de demostración: ','look.store':'Ver ubicación de ejemplo','look.clear':'Reiniciar',
 'rec.button':'Recomendar mi tono','rec.needFace':'Mira a la cámara para analizar tu tono.','rec.done':(b,c)=>`Tono sugerido: base ${b} · colorete ${c}`,
 'cal.confirm':'Coloca una tarjeta gris o blanca en el centro de la imagen. ¿Calibrar ahora?','cal.error':'No se pudo guardar la calibración en este navegador.',
 'export.look':'TU LOOK','export.products':'PRODUCTOS PROBADOS','export.disclaimer':'Vista previa orientativa. El resultado puede variar según la luz y la pantalla.','export.noImage':'No hay una imagen de cámara disponible para exportar.','export.noBlob':'El navegador no pudo crear la imagen.'
},
en:{
 'welcome.eyebrow':'Professional beauty · Virtual experience','welcome.h1':'Your beauty.<br>Your way.','welcome.p':'Discover how our products could look on you.','welcome.start':'Start','welcome.small':'A beauty experience · No commitment',
 'consent.eyebrow':'Your privacy comes first','consent.h2':'We will use your camera to create this virtual try-on experience.','consent.p':'The video is processed on this device; it is not sent or stored. An image is only saved if you download it. If you calibrate the colour, the calibration is stored in this browser. The camera turns off when you leave.','consent.accept':'Accept and continue','consent.no':'Not now',
 'scan.eyebrow':'Virtual try-on','scan.cancel':'Cancel','scan.retry':'Retry camera','scan.c0':'Face detected','scan.c1':'Good lighting','scan.c2':'Correct position',
 'mirror.back':'← Back','mirror.backAria':'Back','mirror.look':'My look','mirror.compare':'Compare','mirror.save':'Save','mirror.calibrate':'Calibrate','mirror.tag':'Choose a product to start.','mirror.before':'Before','mirror.after':'After','mirror.subtle':'Subtle','mirror.intense':'Intense','mirror.intensity':'Intensity','mirror.catalog':'Demo catalog · Fictional products, prices and location',
 'store.title':'Example location','store.close':'Close','store.aisle':'Example aisle','store.section':'Section','store.demo':'The catalog and location are fictional demo data; they do not represent real stock.',
 'save.eyebrow':'Your selection','save.h2':'Your look, ready to save','save.placeholder':'Your look preview will appear here.','save.download':'Download image','save.finish':'Finish','save.keep':'Keep trying','save.previewAlt':'Preview of the created look','save.needProduct':'Try at least one product before saving your look.','save.align':'Align your face with the camera before saving.','save.preparing':'Preparing the image…','save.ready':'Image created on this device. Download it to save it; it has not been uploaded to any server.','save.error':'Could not prepare the image. Go back to the mirror and try again.','save.errorShort':'Could not prepare the image.',
 'cam.prep':'Preparing the camera','cam.permission':'Accept the browser permission to continue.','cam.face':'Place your face here','cam.looking':'Looking at the camera','cam.loadingFace':'Loading face detection…','cam.lost':'Camera lost','cam.lostMsg':'The camera has disconnected. Check the device and try again.','cam.resume':'Could not resume the camera. Go back to the start to try again.','cam.failTitle':'Could not start the try-on','cam.unsupported':'This browser does not offer camera access. Try Chrome or Edge.','cam.denied':'Camera permission was not granted. Enable it in the browser and try again.','cam.notfound':'No connected camera was found.','cam.busy':'The camera is in use by another application. Close it and try again.','cam.security':'Open the app from localhost or an HTTPS connection to use the camera.','cam.generic':'Could not load the camera or face detection. Check your connection and try again.',
 'scan.perfect':'Perfect.','scan.preparing':'We are preparing your experience.',
 'hint.noFace':'We cannot see your face. Look at the camera.','hint.dark':'Low light: move to a brighter area.','hint.yaw':'Look at the camera to see the full result.','hint.detectFail':'Face detection was interrupted. Start the try-on again.','hint.cpu':'Compatibility mode enabled: quality adapts automatically.',
 'quality.auto':'Auto','quality.high':'High','quality.fluid':'Smooth','quality.btn':l=>`Quality: ${l}`,
 'cat.base':'Foundation','cat.blush':'Blush','cat.lips':'Lips','cat.eyes':'Eyes','cat.glow':'Highlighter','cat.contour':'Contour','cat.liner':'Liner','cat.lash':'Lashes','cat.brow':'Brows',
 'fin.Mate':'Matte','fin.Luminoso':'Glow','fin.Satinado':'Satin','fin.Brillo':'Gloss','fin.Glitter':'Glitter','fin.Suave':'Soft','fin.Definido':'Defined','fin.Definida':'Defined','fin.Fino':'Thin','fin.Clásico':'Classic','fin.Alado':'Winged','fin.Natural':'Natural','fin.Volumen':'Volume',
 'prod.try':'Try','shade.selected':'Your selection','look.empty':'You have not tried anything yet.','look.ideas':'Combination ideas from the demo catalog: ','look.store':'See example location','look.clear':'Reset',
 'rec.button':'Recommend my tone','rec.needFace':'Look at the camera to analyse your tone.','rec.done':(b,c)=>`Suggested tone: foundation ${b} · blush ${c}`,
 'cal.confirm':'Place a grey or white card in the centre of the image. Calibrate now?','cal.error':'Could not save the calibration in this browser.',
 'export.look':'YOUR LOOK','export.products':'PRODUCTS TRIED','export.disclaimer':'Indicative preview. The result may vary with lighting and screen.','export.noImage':'No camera image is available to export.','export.noBlob':'The browser could not create the image.'
}
};
export const LANGS=Object.keys(I18N);

// Traduce una clave al idioma dado, con respaldo a español y a la propia clave.
export const translate=(lang,key,...args)=>{const d=I18N[lang]||I18N.es;const v=d[key]??I18N.es[key];return typeof v==='function'?v(...args):(v??key)};

// Elige idioma: preferencia guardada válida o, si no, el del navegador.
export const pickLang=(saved,preferred)=>(saved==='es'||saved==='en')?saved:(/^en/i.test(preferred||'')?'en':'es');
